CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_code TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    api_key_hash TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DISQUALIFIED')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS instruments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL UNIQUE,
    company_name TEXT NOT NULL,
    sector TEXT,
    exchange TEXT NOT NULL DEFAULT 'NYSE/NASDAQ',
    currency TEXT NOT NULL DEFAULT 'USD',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS trading_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trading_date DATE NOT NULL UNIQUE,
    market_open_at TIMESTAMPTZ NOT NULL,
    market_close_at TIMESTAMPTZ NOT NULL,
    submission_open_at TIMESTAMPTZ,
    submission_deadline_at TIMESTAMPTZ,
    market_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (market_status IN ('PENDING', 'DATA_IMPORTED', 'FAILED')),
    execution_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (execution_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    valuation_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (valuation_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    observation_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (observation_status IN ('PENDING', 'GENERATING', 'PUBLISHED', 'FAILED')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CHECK (
        submission_open_at IS NULL OR submission_deadline_at IS NULL
        OR submission_open_at < submission_deadline_at
    )
);

CREATE TABLE IF NOT EXISTS market_bars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trading_day_id BIGINT NOT NULL REFERENCES trading_days(id),
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    open NUMERIC(28, 12) NOT NULL CHECK (open > 0),
    high NUMERIC(28, 12) NOT NULL CHECK (high > 0),
    low NUMERIC(28, 12) NOT NULL CHECK (low > 0),
    close NUMERIC(28, 12) NOT NULL CHECK (close > 0),
    adjusted_open NUMERIC(28, 12) NOT NULL CHECK (adjusted_open > 0),
    adjusted_close NUMERIC(28, 12) NOT NULL CHECK (adjusted_close > 0),
    volume NUMERIC(28, 12) NOT NULL CHECK (volume >= 0),
    source TEXT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (trading_day_id, instrument_id),
    CHECK (high >= low),
    CHECK (high >= open AND high >= close),
    CHECK (low <= open AND low <= close)
);

CREATE INDEX IF NOT EXISTS market_bars_by_instrument_day
    ON market_bars(instrument_id, trading_day_id);

CREATE TABLE IF NOT EXISTS fundamental_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    period_end DATE NOT NULL,
    available_at TIMESTAMPTZ NOT NULL,
    source TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (instrument_id, period_end, source)
);

CREATE INDEX IF NOT EXISTS fundamentals_point_in_time
    ON fundamental_records(instrument_id, available_at);

CREATE TABLE IF NOT EXISTS portfolio_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id),
    trading_day_id BIGINT REFERENCES trading_days(id),
    execution_id BIGINT,
    snapshot_type TEXT NOT NULL
        CHECK (snapshot_type IN ('INITIAL', 'POST_OPEN', 'CLOSE')),
    cash NUMERIC(28, 12) NOT NULL,
    positions_value NUMERIC(28, 12) NOT NULL,
    nav NUMERIC(28, 12) NOT NULL CHECK (nav >= 0),
    gross_exposure NUMERIC(28, 12) NOT NULL DEFAULT 0 CHECK (gross_exposure >= 0),
    drawdown NUMERIC(28, 12) NOT NULL DEFAULT 0,
    effective_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (team_id, trading_day_id, snapshot_type)
);

CREATE TABLE IF NOT EXISTS position_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_snapshot_id BIGINT NOT NULL
        REFERENCES portfolio_snapshots(id) ON DELETE CASCADE,
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    quantity NUMERIC(28, 12) NOT NULL,
    reference_price NUMERIC(28, 12) NOT NULL CHECK (reference_price > 0),
    market_value NUMERIC(28, 12) NOT NULL,
    weight NUMERIC(28, 12) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (portfolio_snapshot_id, instrument_id)
);

CREATE INDEX IF NOT EXISTS positions_by_instrument
    ON position_snapshots(instrument_id, portfolio_snapshot_id);

CREATE TABLE IF NOT EXISTS observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id),
    trading_day_id BIGINT NOT NULL REFERENCES trading_days(id),
    close_portfolio_snapshot_id BIGINT NOT NULL
        REFERENCES portfolio_snapshots(id),
    payload_json JSONB NOT NULL,
    payload_hash TEXT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    first_served_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (team_id, trading_day_id)
);

CREATE INDEX IF NOT EXISTS observations_for_team_day
    ON observations(team_id, trading_day_id);

CREATE TABLE IF NOT EXISTS submission_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id),
    trading_day_id BIGINT REFERENCES trading_days(id),
    request_id TEXT NOT NULL UNIQUE,
    idempotency_key TEXT,
    received_at TIMESTAMPTZ NOT NULL,
    payload_json JSONB,
    payload_hash TEXT,
    outcome TEXT NOT NULL CHECK (outcome IN (
        'ACCEPTED', 'IDEMPOTENT_REPLAY', 'IDEMPOTENCY_CONFLICT',
        'ALREADY_SUBMITTED', 'OUTSIDE_WINDOW', 'UNKNOWN_SESSION',
        'INVALID_REQUEST', 'TEAM_MISMATCH'
    )),
    rejection_reason TEXT,
    details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    CHECK (
        (outcome = 'ACCEPTED' AND rejection_reason IS NULL)
        OR (outcome <> 'ACCEPTED' AND rejection_reason IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS submission_attempts_for_team_day
    ON submission_attempts(team_id, trading_day_id, received_at);

CREATE TABLE IF NOT EXISTS decision_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intake_attempt_id BIGINT UNIQUE REFERENCES submission_attempts(id),
    team_id BIGINT NOT NULL REFERENCES teams(id),
    observation_id BIGINT NOT NULL REFERENCES observations(id),
    signal_day_id BIGINT NOT NULL REFERENCES trading_days(id),
    execution_day_id BIGINT NOT NULL REFERENCES trading_days(id),
    idempotency_key TEXT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    raw_payload_json JSONB NOT NULL,
    payload_hash TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'PARTICIPANT'
        CHECK (source IN ('PARTICIPANT', 'FALLBACK')),
    status TEXT NOT NULL
        CHECK (status IN ('RECEIVED', 'VALIDATED', 'REJECTED', 'QUEUED', 'EXECUTED')),
    rejection_reason TEXT,
    validator_version TEXT,
    validation_policy_json JSONB,
    validation_summary_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    expected_weight_count BIGINT NOT NULL CHECK (expected_weight_count >= 0),
    stored_weight_count BIGINT NOT NULL DEFAULT 0 CHECK (stored_weight_count >= 0),
    sanitized_gross_weight NUMERIC(28, 12),
    weights_processed_at TIMESTAMPTZ,
    agent_version TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (team_id, signal_day_id),
    UNIQUE (team_id, idempotency_key),
    CHECK (signal_day_id <> execution_day_id),
    CHECK (
        (status = 'REJECTED' AND rejection_reason IS NOT NULL)
        OR status <> 'REJECTED'
    ),
    CHECK (stored_weight_count <= expected_weight_count),
    CHECK (
        status IN ('RECEIVED', 'REJECTED')
        OR (
            validator_version IS NOT NULL
            AND validation_policy_json IS NOT NULL
            AND
            stored_weight_count = expected_weight_count
            AND sanitized_gross_weight IS NOT NULL
            AND weights_processed_at IS NOT NULL
        )
    )
);

CREATE INDEX IF NOT EXISTS submissions_for_execution_day
    ON decision_submissions(execution_day_id, status);

CREATE TABLE IF NOT EXISTS submission_weights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL
        REFERENCES decision_submissions(id) ON DELETE CASCADE,
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    was_provided BOOLEAN NOT NULL,
    raw_weight NUMERIC(28, 12),
    sanitized_weight NUMERIC(28, 12) NOT NULL,
    validation_codes_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (submission_id, instrument_id),
    CHECK (was_provided = TRUE OR raw_weight IS NULL)
);

CREATE INDEX IF NOT EXISTS weights_for_submission
    ON submission_weights(submission_id, instrument_id);

CREATE TABLE IF NOT EXISTS executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id),
    submission_id BIGINT NOT NULL UNIQUE REFERENCES decision_submissions(id),
    trading_day_id BIGINT NOT NULL REFERENCES trading_days(id),
    status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    engine_version TEXT NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ,
    processed_at TIMESTAMPTZ,
    nav_before NUMERIC(28, 12),
    cash_before NUMERIC(28, 12),
    cash_after NUMERIC(28, 12),
    total_buy_value NUMERIC(28, 12) NOT NULL DEFAULT 0,
    total_sell_value NUMERIC(28, 12) NOT NULL DEFAULT 0,
    total_fee NUMERIC(28, 12) NOT NULL DEFAULT 0,
    error_code TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (team_id, trading_day_id)
);

CREATE INDEX IF NOT EXISTS pending_executions
    ON executions(trading_day_id, status);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL REFERENCES executions(id) ON DELETE CASCADE,
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    side TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
    shares_before NUMERIC(28, 12) NOT NULL,
    target_shares NUMERIC(28, 12) NOT NULL,
    quantity NUMERIC(28, 12) NOT NULL CHECK (quantity >= 0),
    price NUMERIC(28, 12) NOT NULL CHECK (price > 0),
    gross_amount NUMERIC(28, 12) NOT NULL CHECK (gross_amount >= 0),
    fee NUMERIC(28, 12) NOT NULL CHECK (fee >= 0),
    cash_change NUMERIC(28, 12) NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('COMPLETED', 'SKIPPED', 'FAILED')),
    effective_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (execution_id, instrument_id)
);

CREATE INDEX IF NOT EXISTS transactions_by_instrument
    ON transactions(instrument_id, execution_id);

CREATE TABLE IF NOT EXISTS cash_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id),
    trading_day_id BIGINT REFERENCES trading_days(id),
    execution_id BIGINT,
    transaction_id BIGINT REFERENCES transactions(id),
    event_type TEXT NOT NULL
        CHECK (event_type IN ('INITIAL_CAPITAL', 'TRADE', 'FEE', 'DIVIDEND', 'ADJUSTMENT')),
    amount NUMERIC(28, 12) NOT NULL,
    balance_before NUMERIC(28, 12) NOT NULL,
    balance_after NUMERIC(28, 12) NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS cash_ledger_for_team
    ON cash_ledger(team_id, effective_at, id);

CREATE TABLE IF NOT EXISTS daily_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id),
    trading_day_id BIGINT NOT NULL REFERENCES trading_days(id),
    close_portfolio_snapshot_id BIGINT NOT NULL UNIQUE
        REFERENCES portfolio_snapshots(id),
    previous_close_nav NUMERIC(28, 12) NOT NULL CHECK (previous_close_nav >= 0),
    current_close_nav NUMERIC(28, 12) NOT NULL CHECK (current_close_nav >= 0),
    daily_return NUMERIC(28, 12) NOT NULL,
    cumulative_return NUMERIC(28, 12) NOT NULL,
    transaction_cost NUMERIC(28, 12) NOT NULL DEFAULT 0 CHECK (transaction_cost >= 0),
    turnover NUMERIC(28, 12) NOT NULL DEFAULT 0 CHECK (turnover >= 0),
    drawdown NUMERIC(28, 12) NOT NULL,
    calculated_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (team_id, trading_day_id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id),
    trading_day_id BIGINT REFERENCES trading_days(id),
    actor_type TEXT NOT NULL CHECK (actor_type IN ('SYSTEM', 'TEAM', 'ADMIN')),
    actor_id TEXT,
    event_type TEXT NOT NULL,
    entity_type TEXT,
    entity_id BIGINT,
    request_id TEXT,
    details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS audit_by_day_type
    ON audit_logs(trading_day_id, event_type, created_at);

CREATE OR REPLACE VIEW v_submission_weight_details AS
SELECT
    ds.id AS submission_id,
    t.team_code,
    signal_day.trading_date AS signal_date,
    execution_day.trading_date AS execution_date,
    i.ticker,
    sw.was_provided,
    sw.raw_weight,
    sw.sanitized_weight,
    sw.validation_codes_json,
    ds.status AS submission_status
FROM submission_weights sw
JOIN decision_submissions ds ON ds.id = sw.submission_id
JOIN teams t ON t.id = ds.team_id
JOIN trading_days signal_day ON signal_day.id = ds.signal_day_id
JOIN trading_days execution_day ON execution_day.id = ds.execution_day_id
JOIN instruments i ON i.id = sw.instrument_id;

CREATE OR REPLACE VIEW v_transaction_history AS
SELECT
    tx.id AS transaction_id,
    e.id AS execution_id,
    ds.id AS submission_id,
    t.team_code,
    td.trading_date,
    i.ticker,
    tx.side,
    tx.quantity,
    tx.price,
    tx.gross_amount,
    tx.fee,
    tx.cash_change,
    tx.status,
    tx.effective_at,
    tx.processed_at
FROM transactions tx
JOIN executions e ON e.id = tx.execution_id
JOIN decision_submissions ds ON ds.id = e.submission_id
JOIN teams t ON t.id = e.team_id
JOIN trading_days td ON td.id = e.trading_day_id
JOIN instruments i ON i.id = tx.instrument_id;

CREATE OR REPLACE VIEW v_portfolio_positions AS
SELECT
    ps.id AS portfolio_snapshot_id,
    t.team_code,
    td.trading_date,
    ps.snapshot_type,
    ps.cash,
    ps.positions_value,
    ps.nav,
    i.ticker,
    pos.quantity,
    pos.reference_price,
    pos.market_value,
    pos.weight,
    ps.effective_at
FROM portfolio_snapshots ps
JOIN teams t ON t.id = ps.team_id
LEFT JOIN trading_days td ON td.id = ps.trading_day_id
LEFT JOIN position_snapshots pos ON pos.portfolio_snapshot_id = ps.id
LEFT JOIN instruments i ON i.id = pos.instrument_id;

DO $$
BEGIN
    ALTER TABLE decision_submissions
        ALTER COLUMN intake_attempt_id DROP NOT NULL;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'portfolio_snapshots_execution_id_fkey') THEN
        ALTER TABLE portfolio_snapshots
            ADD CONSTRAINT portfolio_snapshots_execution_id_fkey
            FOREIGN KEY (execution_id) REFERENCES executions(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'cash_ledger_execution_id_fkey') THEN
        ALTER TABLE cash_ledger
            ADD CONSTRAINT cash_ledger_execution_id_fkey
            FOREIGN KEY (execution_id) REFERENCES executions(id);
    END IF;
END $$;
